apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-cache-claim
spec:
  resources:
    requests:
      storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
