apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis-cache-deployment
  name: redis-cache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cache-deployment
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-cache-deployment
    spec:
      containers:
        - name: redis-cache-deployment
          image: redis
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          resources: { }
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis-cache-claim
status: { }